 server:
   port: 8080

security:
  basic:
    enabled: false # turn of securing our application endpoints

management:
  security:
    enabled: false # turn of securing the actuator endpoints
	
security: 
	user:
		name: test